### ISSUE TITLE
Uploading file causes FTP server to dump core

### ISSUE THREAD

**Issue by H-Reynolds** [MilesWinston23/Scene2#1]
* Start Bee Flogger
* Create an unnamed document simply containing the letter “a”
* Click on the FTP button on the toolbar
* Try to ftp to your server

BUG: Observe; the ftp server is no longer responding. Indeed ps -augx shows that it is not even running and there is a core dump in /.

EXPECTED: No crash

**Comment by DuraKeonangphane** [comment]
Not our code, Jill, that’s just proftpd which comes with Linux.

**Comment by DuraKeonangphane** [comment]
Mikey, can you look at this? Maybe your client code is doing something wrong.

**Comment by MilesWinston23** [comment]
I think I was passing the user name instead of the password or something…

**Comment by H-Reynolds** [comment]
Mikey this is still broken man.

**Comment by MilesWinston23** [comment]
Whoa. That’s strange. Lemme debug this.

**Comment by H-Reynolds** [comment]
yay looks good :thumbs-up:
